""" Contains the response generated by a command request. """

class CommandResponse(object):
    """ Object to return a command response. """

    def should_power_on(self):
        """ Should we power on the relay? """
        if self.should_power_off():
            return False

        return self.__turn_on__

    def should_power_off(self):
        """ Should we power off the relay? """
        return self.__turn_off__

    def get_messages(self):
        """ Returns the message """
        if self.__message__ is None:
            return ""

        return self.__message__

    def __init__(self, turn_on, turn_off, message):
        self.__turn_on__ = turn_on
        self.__turn_off__ = turn_off
        self.__message__ = message
