"""
Module to hold common text messages and strings.
"""


QUIT = "QUIT"
MAX_TIME = "MAX_TIME"
GAS_WARNING = "Gas warning"
GAS_OK = "OK"
CHECK_SIGNAL = "SIGNAL"
CHECK_BATTERY = "BATTERY"
HEATER_OFF = "OFF"
HEATER_ON = "ON"
PI_WARMER_OFF = "SHUTDOWN"
PI_WARMER_RESTART = "RESTART"
STATUS = "STATUS"
HELP = "HELP"
ERROR = "ERROR"
NOOP = "NOOP"
